### ISSUE TITLE
High Latency

### ISSUE THREAD

**Issue by jbeck28** [gbartyzel/ros2_net_ft_driver#3]
Hello, 

I'm very happy to see this driver appear for ROS2. However, upon getting it working with an ATI Gamma Net FT sensor, I find that there is a significant amount of latency between my touching the sensor and a corresponding change in forces appearing on the published topic. I'm wondering if you've any idea what may be the cause? I don't see this issue with the ROS1 driver. My only guess is possibly QoS settings? 

Another thing, I've noticed the driver automatically biases the sensor on startup. Is there any way to disable that behavior? 

Thanks,
Josh

**Comment by gbartyzel** [comment]
Hello @jbeck28 

I'm delighted that you found this driver helpful for your project and you were able to run this with ATI Net FT, because in my lab I have only access to ATI AXIA and OnRobot HEX. Im not sure if this is caused by the QoS, you can check here https://github.com/ros-controls/ros2_controllers/tree/master/force_torque_sensor_broadcaster what QoS configuration is used. Moreover, in the ros2_control documentation ther suggest to use rt-preempt kernle for best performance, maybe this can solve the problem. Nevertheless, I'll try to investigate this problem, but feel free to create PR ;)

And about biasing. You're right, sensor is biased on the activation. It was work around for lack of such functionality in the ft sensor broadcaster. If this is a problem, I can make this an optional functionality.

Greg.

**Comment by jbeck28** [comment]
Hi Greg, 

Thanks for the information! Sensor biasing being optional would be an awesome feature! 

Just wanted to provide the findings of what little testing I've done in the last 2 days. I ran the driver with the preempt_rt kernel patch and still experienced the same latency. However, just for fun I tried changing `update_rate` in `net_ft_broadcaster.yaml` from 500 to 2000, and I found this eliminated the latency. Similarly, since I'm using this with an ABB robot, I tried changing the update rate to 250 (this is the max control frequency for ABB robots) and the latency got worse! Very interesting

Josh

**Comment by gbartyzel** [comment]
@jbeck28 maybe try playing with `rdt_sampling_rate`. Check if this also changes the sensor's `ADC sampling rate` (go to the website).

**Comment by gbartyzel** [comment]
@jbeck28 Optional biasing is added! ;)

**Comment by zimmerman-pliant** [comment]
I'm having this problem too with my ATI Omega85 (driver install and setup worked great, though, thanks!)  I'm using the Rolling branch on Jazzy.

It does seem like increasing `update_rate` to 2kHz helps but I'll probably look for another solution. I am also not yet running a `PREEMPT_RT` kernel but that'll be in the future on the project.

I noticed I'm getting a ton of lost packets on `/net_ft_diagnostic_broadcaster/net_ft_diagnostic`:

```yaml
header:
  stamp:
    sec: 1738282200
    nanosec: 455603780
  frame_id: ''
status:
- level: "\0"
  name: ''
  message: ''
  hardware_id: ''
  values:
  - key: System status
    value: '0x00000000'
  - key: Good packets
    value: '18333'
  - key: Lost packets
    value: '236109'
  - key: Out-of-order packets
    value: '0'
```

I tried changing the RDT buffer size from the default of 1 but that didn't seem to have an effect, >10x packets dropped as coming through.

![Image](https://github.com/user-attachments/assets/b046bb01-92a7-46c1-8147-f3a3c77bfef4)

This is all with `sensor_type:=ati rdt_sampling_rate:=500` but I tried with lower RDT sampling rate and it didn't change anything so far. Where should I look on the web interface for the ADC sampling rate?

I'll be working with it regularly, so I'll post any further findings here as I go along and make a PR if I find something.

**Comment by zimmerman-pliant** [comment]
Setting the update rate to 2kHz improves the packet throughput from about 7% to 29% and reduces the latency to something that's hard to notice by eye watching it in RViz.

**Comment by zimmerman-pliant** [comment]
Looks like the RDT data rate request is not getting through to the Omega85 and it's running at the max rate which is default 7kHz.

I tried setting the max rate in the GUI to 500Hz:

![Image](https://github.com/user-attachments/assets/c50ce406-e669-4c59-a92e-8cb48fe9b64b)

And I ran for 30s and get no dropped packets in the diagnostics and a total count consistent with approximately 500Hz rate:

```yaml
---
header:
  stamp:
    sec: 1738797720
    nanosec: 411288407
  frame_id: ''
status:
- level: "\0"
  name: ''
  message: ''
  hardware_id: ''
  values:
  - key: System status
    value: '0x00000000'
  - key: Good packets
    value: '14759'
  - key: Lost packets
    value: '0'
  - key: Out-of-order packets
    value: '0'
---
``` 

Perceptible latency in RViz is entirely eliminated.

My other dropped packets observations with the default and increased ROS 2 control update rate settings are consistent with a 7kHz incoming rate: 500/7000 = 7%, 2000/7000 = 28.5% 

~I also noticed that `use_hardware_bias:=true` does not seem to zero out the sensor.~

EDIT: this is just user error on my part, `use_hardware_biasing:=true` at launch works fine.

Will try to debug the connection back to the sensor and see why it doesn't seem to be accepting commands. For now, setting the max RDT rate to 500Hz seems to be a good workaround.

EDIT: see #16 for a potential fix.
